#ifndef MCU_PINS_H_
#define MCU_PINS_H_

#include <avr/io.h>

#define ACCELEROMETER_X_PIN (_BV(PORTA7))
#define ACCELEROMETER_Y_PIN (_BV(PORTA6))
#define ACCELEROMETER_Z_PIN (_BV(PORTA5))
#define BARO_PRESSURE_PIN (_BV(PORTA3))
#define BATTERY_VOLTAGE_PIN (_BV(PORTA4))
#define GYRO_X_PIN (_BV(PORTA1))
#define GYRO_Y_PIN (_BV(PORTA2))
#define GYRO_Z_PIN (_BV(PORTA0))
#define LED_GREEN_PIN (_BV(PORTB1))
#define LED_RED_PIN (_BV(PORTB0))

#define LED_GREEN_PORT (PORTB)
#define LED_RED_PORT (PORTB)

#define LED_GREEN_DDR (DDRB)
#define LED_RED_DDR (DDRB)

#define LED_GREEN_OFF (LED_GREEN_PORT |= LED_GREEN_PIN)
#define LED_GREEN_ON (LED_GREEN_PORT &= ~LED_GREEN_PIN)
#define LED_GREEN_TOGGLE (LED_GREEN_PORT ^= LED_GREEN_PIN)
#define LED_RED_OFF (LED_RED_PORT &= ~LED_RED_PIN)
#define LED_RED_ON (LED_RED_PORT |= LED_RED_PIN)
#define LED_RED_TOGGLE (LED_RED_PORT ^= LED_RED_PIN)

#endif //MCU_PINS_H_
