#ifndef MCU_PINS_H_
#define MCU_PINS_H_


#include <avr/io.h>


// ADC
#define ADC_DDR (DDRA)

#define ACCELEROMETER_X_PIN (_BV(PORTA7))
#define ACCELEROMETER_X_PORT (PORTA)

#define ACCELEROMETER_Y_PIN (_BV(PORTA6))
#define ACCELEROMETER_Y_PORT (PORTA)

#define ACCELEROMETER_Z_PIN (_BV(PORTA5))
#define ACCELEROMETER_Z_PORT (PORTA)

#define BARO_PRESSURE_PIN (_BV(PORTA3))
#define BARO_PRESSURE_PORT (PORTA)

#define BATTERY_VOLTAGE_PIN (_BV(PORTA4))
#define BATTERY_VOLTAGE_PORT (PORTA)

#define GYRO_X_PIN (_BV(PORTA1))
#define GYRO_X_PORT (PORTA)

#define GYRO_Y_PIN (_BV(PORTA2))
#define GYRO_Y_PORT (PORTA)

#define GYRO_Z_PIN (_BV(PORTA0))
#define GYRO_Z_PORT (PORTA)


// LED
#define LED_DDR (DDRB)

#define GREEN_LED_PIN (_BV(PORTB1))
#define GREEN_LED_PORT (PORTB)

#define RED_LED_PIN (_BV(PORTB0))
#define RED_LED_PORT (PORTB)


#endif  // MCU_PINS_H_
